# config.py
SCREEN_WIDTH = 1366
SCREEN_HEIGHT = 768
BACKGROUND_COLOR = (255, 255, 255)
COOKIE_SIZE = 100  # Changed from PANCAKE_SIZE
INITIAL_COOKIE_POS = [(400, 500), (400, 450), (400, 400)]  # Changed from INITIAL_PANCAKE_POS
REGULAR_COOKIE_IMAGE = "Assets/cookie.png"  # Changed from REGULAR_PANCAKE_IMAGE
STAR_COOKIE_IMAGE = "Assets/cookie.png"  # Changed from STAR_PANCAKE_IMAGE